[package]
name = "raster"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.43"
approx = "0.5.0"
eframe = "0.14.0"
image = "0.23.14"
lazy_static = "1.4.0"
nalgebra = "0.29.0"

[profile.release]
debug = true
